### PR TITLE
Made 'output_path' as non-mandatory field

### PR DESCRIPTION
**Pull request by rajendrakrp**

### CODE REVIEW

**Comment by alanhamlett** [comment]
Can you rebase and resolve the merge conflicts?

**Comment by alanhamlett** [comment]
Also, can you update the readme changing this line:
`# Use False instead of output path to save pdf to a variable`
to:
`# Without output_path, PDF is returned for assigning to a variable`

**Comment by yohanboniface** [comment]
@alanhamlett https://github.com/JazzCore/python-pdfkit/pull/181 brand new ;)

**Comment by JazzCore** [comment]
Fixed in #181, now merged in master, thanks!

**Pull request closed without merging**
