### PR TITLE
Appeding IOError messages & updating stderr with proper output

### PR DESCRIPTION
**Pull request by fasihahmad**
Appeding IOError messages & updating stderr with proper output

### CODE REVIEW

**Comment by fasihahmad** [comment]
@JazzCore please have a look at #68 PR

**Comment by wowkin2** [comment]
@JazzCore, please review this, I think that this can help with debug process.

**Comment by fasihahmad** [comment]
Correct @wowkin2 this is really helping in debugging process.

**Comment by JazzCore** [comment]
This breaks some tests on python 3+, I'll try to look into this in a few days

**Comment by fasihahmad** [comment]
Thanks @JazzCore I have also committed exact changes for python3 support

**Comment by JazzCore** [comment]
This is super fast, you rock :) Thanks!

**Pull request merged**
